// Generated by gencpp from file flask_demo/hello.msg
// DO NOT EDIT!


#ifndef FLASK_DEMO_MESSAGE_HELLO_H
#define FLASK_DEMO_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flask_demo
{
template <class ContainerAllocator>
struct hello_
{
  typedef hello_<ContainerAllocator> Type;

  hello_()
    : hello()  {
    }
  hello_(const ContainerAllocator& _alloc)
    : hello(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hello_type;
  _hello_type hello;





  typedef boost::shared_ptr< ::flask_demo::hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flask_demo::hello_<ContainerAllocator> const> ConstPtr;

}; // struct hello_

typedef ::flask_demo::hello_<std::allocator<void> > hello;

typedef boost::shared_ptr< ::flask_demo::hello > helloPtr;
typedef boost::shared_ptr< ::flask_demo::hello const> helloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flask_demo::hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flask_demo::hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flask_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'flask_demo': ['/home/patrick/hello_ws/src/flask_demo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flask_demo::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flask_demo::hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flask_demo::hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flask_demo::hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flask_demo::hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flask_demo::hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flask_demo::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa1e4c96cf56304cea7e883d117e24f3";
  }

  static const char* value(const ::flask_demo::hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa1e4c96cf56304cULL;
  static const uint64_t static_value2 = 0xea7e883d117e24f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::flask_demo::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flask_demo/hello";
  }

  static const char* value(const ::flask_demo::hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flask_demo::hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string hello\n\
";
  }

  static const char* value(const ::flask_demo::hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flask_demo::hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hello);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flask_demo::hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flask_demo::hello_<ContainerAllocator>& v)
  {
    s << indent << "hello: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hello);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLASK_DEMO_MESSAGE_HELLO_H
